// Generated by CoffeeScript 1.7.1
(function() {
  var scrollTopBegin;

  $(function() {
    var direction, first, second, third;
    first = new wheelman.Zone(0, 500, $('#first'));
    first.addFade(0, 500, direction = "out");
    second = new wheelman.Zone(500, 1000, $('#second'));
    second.addFade(0, 350);
    third = new wheelman.Zone(1000, 1500, $('#third'));
    return third.addFeature(0, 1, 200, 120, 'right', direction = "in", $('img'));
  });

  $(function() {
    return $(window).scroll(function() {
      var scrollTop;
      scrollTop = $(window).scrollTop();
      if (scrollTop % 2 === 1) {
        return wheelman.scrollEm(scrollTop);
      }
    });
  });

  scrollTopBegin = $(window).scrollTop();

  wheelman.scrollEm(scrollTopBegin);

}).call(this);
